### PR TITLE
Update models.cfg

### PR DESCRIPTION
**Pull request by dc-redeclipse**
fix path for model "dc/cube_1x" and mmodel "dc/cube_4x"

Fixes #

Changes proposed in this request:
Path fixed in cfg.

@qreeves can you also remove 
data_cube_1x and data_cube_4x ?
They are old and already replaced by cube_1x and cube_4x in this pr.

### CODE REVIEW

**Comment by SniperGoth** [comment]
You don't need two versions of the same model with different scales, mind you.
Just scale one in-game.

**Comment by dc-redeclipse** [comment]
@SniperGoth damit! I forget to fix that!

**Comment by cloudziq** [comment]
you don't need to close PR, make fixes and PR again. You can just make fixes, commit them and push changes

**Comment by dc-redeclipse** [comment]
yeah you are right too.

**Pull request closed without merging**
