### PR TITLE
dc-mapmodels-v3

### PR DESCRIPTION
**Pull request by dc-redeclipse**
Fixes #

Changes proposed in this request:
- update mapmodels

@qreeves can you also remove both folders data_cube_1x and data_cube_4x ?
They are old and replaced both by the folder cube in this pr.

### CODE REVIEW

**Comment by cloudziq** [comment]
why you not removed these two folders by yourself?  strange

**Comment by dc-redeclipse** [comment]
> why you not removed these two folders by yourself? strange

I had no permimission for that. If I could do it myself and if I had the right to do so, I wouldn't ask.

**Comment by cloudziq** [comment]
you have no permission to delete own folders on local copy of repo?   :/

**Comment by dc-redeclipse** [comment]
I deleted it local allready but git exclude the del of it from the pr. I dont know why but it is what it is.

**Comment by qreeves** [comment]
> you have no permission to delete own folders on local copy of repo? :/

It's fine, @dc-de has trouble working with Git and I've already said I'll take care of any issues.

**Comment by qreeves** [comment]
> I deleted it local allready but git exclude the del of it from the pr. I dont know why but it is what it is.

If you're interested: `git rm path/to/file` instead of just deleting it.

**Comment by dc-redeclipse** [comment]
@qreeves of course I am! I like to learn this. Thank you for the tipp I will try this way to deleting folders next time I promise.

**Pull request merged**
